### ISSUE TITLE
Install instructions 

### ISSUE THREAD

**Issue by getcontrol** [iamkonrad/KYC-and-banking-DJANGO-web-APP#1]
Interesting project can you add Install instructions /

**Comment by iamkonrad** [comment]
Hi, I am not sure whether this method will work the same with your OS. In requirements.txt you have a list of all the libraries you need for this app to work correctly. I am mostly familiar with PyCharm at this point, If you use PyCharm you basically open the project try to open any py file inside it and requirements.txt will load automatically asking whether you want to install all the requirements. Next you need to configure an interpreter, by providing the path to your Python and specifying the venv. Important point is, this APP IS NOT FINISHED, I was working on it for some time, but then I found some other projects to work on and it's waiting for some better times when I'll have more time to get back to it, but feel free to use it and adapt it.
